# Generated by Django 4.1.3 on 2023-01-15 11:12

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_address_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[cart.models.validate_phone_number]),
        ),
    ]
