# Generated by Django 4.1.3 on 2023-01-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='count',
            new_name='orderdetail_count',
        ),
    ]
