# Generated by Django 4.1.3 on 2023-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_takhfif_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_price',
            field=models.BooleanField(default=False),
        ),
    ]
