# Generated by Django 4.1.3 on 2023-01-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_on_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_price',
        ),
    ]
