# Generated by Django 4.1.3 on 2023-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_comment_title_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.FloatField(default=1),
        ),
    ]
