# Generated by Django 4.1.3 on 2023-01-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_comment_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
