# Generated by Django 4.1.3 on 2023-01-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_comment_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='point',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
