# Generated by Django 4.1.3 on 2023-01-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusgeneral',
            name='text2',
            field=models.TextField(),
        ),
    ]
