# Generated by Django 4.1.3 on 2023-01-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuskeeper',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactuskeeper',
            old_name='title',
            new_name='subject',
        ),
    ]
