# Generated by Django 4.1.3 on 2023-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_rename_text_contactuskeeper_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=155, unique=True),
        ),
    ]
