# Generated by Django 4.1.3 on 2023-01-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabligh',
            name='alt',
            field=models.CharField(default='عکس', max_length=50),
        ),
        migrations.AddField(
            model_name='tabligh',
            name='text2',
            field=models.CharField(max_length=100, null=True, verbose_name='2متن'),
        ),
    ]
