# Generated by Django 4.1.3 on 2023-01-04 08:49

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(max_length=20, null=True, verbose_name='سایز'),
        ),
    ]
