# Generated by Django 4.1.3 on 2023-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_onsale_alter_tabligh_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsale',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
