# Generated by Django 4.1.3 on 2023-01-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_token'),
        ('home', '0004_alter_wishlist_color_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
