# Generated by Django 4.1.3 on 2023-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_on_price'),
        ('home', '0004_onsale_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsale',
            name='products',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
