# Generated by Django 4.1.3 on 2023-01-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_on_price'),
        ('account', '0003_user_token'),
        ('home', '0005_onsale_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
