# Generated by Django 4.1.3 on 2023-01-06 15:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_wishlist_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
