# Generated by Django 4.1.3 on 2023-01-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
